[pytest]
# Quitamos -s y añadimos configuración de logs
addopts = --tb=no -q
log_cli = true
log_cli_level = INFO
log_cli_format = %(message)s

# Indica que python/ debe añadirse al PYTHONPATH (para que `utils` sea importable)
pythonpath = python
# Directorio donde pytest buscará los tests por defecto
testpaths = python/trials
# Patrones de archivos que pytest debe considerar como tests
python_files = *.py
